---
abstract: 'Unicode Box Drawing testing class.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Unicode-Test-BoxDrawing
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  English: 0
  Error::Pure: 0
  List::MoreUtils: 0
  Readonly: 0
  Unicode::UTF8: 0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Text-Unicode-Test-BoxDrawing/issues
  homepage: https://github.com/michal-josef-spacek/Text-Unicode-Test-BoxDrawing
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Text-Unicode-Test-BoxDrawing
version: '0.01'
